import { EMPTY_FILTERS, DEFAULT_AMOUNT, DEFAULT_CURRENCY, INITIAL_FORM_DETAILS_STATE } from './initialStates';
import { BACK_BUTTON_SIZE, CALC_DEBOUNCE_TIME, RIGHT_SPACER_WIDTH, SPLASH_DURATION } from './layout';
import { MOCK_DATA } from '@/__mocks__/data/mockData';
import { ACCOUNT_SECURITY, BILLER_CATEGORIES, MENU_SVG_ICONS, NOTIFICATIONS, ONBOARDING_IMGS, PROFILE, PROFILE_IMAGE_URI, SETTINGS } from './navigationItems';
import { AUTOPAY_STATUS, PAYMENT_OPTIONS, STATUS_LABELS } from './paymentOptions';
import { AQWEB_URL, ERRORS, SUCCESS, WEBVIEW } from './enrollment';
import { ROUTES } from './routes';
import { SECURE_STORE_KEYS, STORAGE_ONBOARD_KEY } from './storageKeys';
import { OBJECT_VALUE_KEYS, PASSWORD_RULE_TEXTS, VALIDATORS } from './validators';

export const COMMON = {
  SPLASH_DURATION,
  PASSWORD_RULE_TEXTS,
  ONBOARDING_IMGS,
  BILLER_CATEGORIES,
  MENU_SVG_ICONS,
  PAYMENT_OPTIONS,
  BACK_BUTTON_SIZE,
  RIGHT_SPACER_WIDTH,
  CALC_DEBOUNCE_TIME,
  SETTINGS,
  ACCOUNT_SECURITY,
  NOTIFICATIONS,
  PROFILE,
  PROFILE_IMAGE_URI,
  ROUTES,
  VALIDATORS,
  SECURE_STORE_KEYS,
  AUTOPAY_STATUS,
  STATUS_LABELS,
  EMPTY_FILTERS,
  STORAGE_ONBOARD_KEY,
  ERRORS,
  SUCCESS,
  INITIAL_FORM_DETAILS_STATE,
  DEFAULT_CURRENCY,
  DEFAULT_AMOUNT,
  OBJECT_VALUE_KEYS,
  WEBVIEW,
  AQWEB_URL,
  MOCK_DATA,
};
