export const SPLASH_DURATION = 2000;

export const BACK_BUTTON_SIZE = 40;

export const RIGHT_SPACER_WIDTH = 40;

export const CALC_DEBOUNCE_TIME = 1000;

export const NAV_HEADER_VERTICAL_PADDING = 12;

export const NAV_HEADER_DEFAULT_HORIZONTAL_PADDING = 24;

export const NAV_HEADER_OUTLINED_BUTTON_SIZE = 44;

export const NAV_HEADER_OUTLINED_BOTTOM_PADDING = 8;

export const NAV_HEADER_OUTLINED_HORIZONTAL_PADDING = 20;
