import { Colors } from '@/styles/common/colors';
import { FontSizes } from '@/styles/common/typography';
import { StyleSheet } from 'react-native';

export const enrollmentDetailsStyles = StyleSheet.create({
  screenContent: {
    backgroundColor: Colors.neutral02,
    paddingBottom: 40,
  },
  screenInner: {
    alignSelf: 'center',
    maxWidth: 960,
    width: '100%',
  },
  contentLayout: {
    gap: 12,
  },
  heroCard: {
    backgroundColor: Colors.neutral01,
    borderColor: Colors.neutral04,
    borderRadius: 16,
    borderWidth: 1,
    padding: 18,
    shadowColor: Colors.neutral10,
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
  },
  heroHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
  },
  heroIdentity: {
    flex: 1,
    minWidth: 0,
  },
  merchantName: {
    color: Colors.neutral09,
    fontSize: FontSizes.extraLarge,
    letterSpacing: -0.2,
    lineHeight: 28,
  },
  paymentType: {
    color: Colors.maroon10,
    lineHeight: 18,
    marginTop: 2,
  },
  description: {
    color: Colors.neutral08,
    lineHeight: 20,
    marginTop: 12,
  },
  referencePanel: {
    alignItems: 'center',
    backgroundColor: Colors.maroon01,
    borderColor: Colors.maroon02,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    marginTop: 16,
    minHeight: 58,
    paddingLeft: 14,
    paddingRight: 7,
    paddingVertical: 7,
  },
  referenceTextGroup: {
    flex: 1,
    minWidth: 0,
  },
  referenceLabel: {
    color: Colors.neutral07,
    letterSpacing: 0.7,
    lineHeight: 14,
  },
  referenceValue: {
    color: Colors.neutral09,
    fontSize: FontSizes.base,
    letterSpacing: 0.2,
    lineHeight: 21,
    marginTop: 2,
  },
  copyButton: {
    alignItems: 'center',
    backgroundColor: Colors.neutral01,
    borderColor: Colors.maroon03,
    borderRadius: 10,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    marginLeft: 10,
    width: 44,
  },
  copyButtonPressed: {
    backgroundColor: Colors.red02,
    borderColor: Colors.red10,
  },
  copyButtonFocused: {
    borderColor: Colors.info10,
    borderWidth: 2,
  },
  paymentSummaryCard: {
    backgroundColor: Colors.maroon10,
    borderRadius: 18,
    overflow: 'hidden',
    padding: 20,
  },
  amountLabel: {
    color: Colors.red04,
    letterSpacing: 1,
    lineHeight: 18,
  },
  monthlyAmount: {
    color: Colors.neutral01,
    fontSize: 34,
    letterSpacing: -0.8,
    lineHeight: 45,
    marginTop: 2,
  },
  estimatedTotalPill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: Colors.maroon09,
    borderRadius: 999,
    flexDirection: 'row',
    gap: 6,
    marginTop: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  estimatedTotalLabel: {
    color: Colors.maroon02,
    lineHeight: 15,
  },
  estimatedTotalValue: {
    color: Colors.neutral01,
    lineHeight: 18,
  },
  summaryMetrics: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 18,
  },
  summaryMetric: {
    backgroundColor: Colors.maroon09,
    borderColor: Colors.maroon08,
    borderRadius: 10,
    borderWidth: 1,
    flexBasis: '47%',
    flexGrow: 1,
    minHeight: 64,
    paddingHorizontal: 11,
    paddingVertical: 10,
  },
  summaryMetricWide: {
    flexBasis: '22%',
  },
  summaryMetricLabel: {
    color: Colors.maroon03,
    lineHeight: 15,
  },
  summaryMetricValue: {
    color: Colors.neutral01,
    lineHeight: 19,
    marginTop: 3,
  },
  sectionCard: {
    backgroundColor: Colors.neutral01,
    borderColor: Colors.neutral04,
    borderRadius: 16,
    borderWidth: 1,
    padding: 18,
  },
  secondaryCard: {
    backgroundColor: Colors.maroon01,
    borderColor: Colors.maroon02,
  },
  sectionTitleGroup: {
    flex: 1,
    minWidth: 0,
  },
  sectionTitle: {
    color: Colors.neutral09,
    fontSize: FontSizes.medium,
    lineHeight: 23,
  },
  sectionDescription: {
    color: Colors.neutral07,
    lineHeight: 17,
    marginTop: 2,
  },
  progressHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
  },
  progressPercentage: {
    color: Colors.maroon10,
    fontSize: FontSizes.large,
    lineHeight: 24,
  },
  progressBar: {
    height: 8,
    marginTop: 16,
  },
  progressDetails: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 16,
  },
  progressDetail: {
    backgroundColor: Colors.neutral02,
    borderRadius: 10,
    flexBasis: '46%',
    flexGrow: 1,
    minHeight: 58,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  progressDetailLabel: {
    color: Colors.neutral07,
    letterSpacing: 0.5,
    lineHeight: 14,
  },
  progressDetailValue: {
    color: Colors.neutral09,
    lineHeight: 18,
    marginTop: 3,
  },
  unavailableText: {
    color: Colors.neutral07,
    lineHeight: 20,
    marginTop: 14,
  },
  detailsGrid: {
    gap: 12,
  },
  detailsGridWide: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  gridCard: {
    width: '100%',
  },
  gridCardWide: {
    flexBasis: '48%',
    flexGrow: 1,
    width: 'auto',
  },
  cardTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  paymentIconFrame: {
    alignItems: 'center',
    backgroundColor: Colors.neutral01,
    borderColor: Colors.neutral04,
    borderRadius: 9,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    marginRight: 11,
    width: 52,
  },
  cardTitleText: {
    flex: 1,
    minWidth: 0,
  },
  detailRows: {
    marginTop: 10,
  },
  detailRow: {
    alignItems: 'flex-start',
    borderTopColor: Colors.neutral04,
    borderTopWidth: 1,
    flexDirection: 'row',
    minHeight: 48,
    paddingVertical: 12,
  },
  detailLabel: {
    color: Colors.neutral07,
    flex: 0.9,
    lineHeight: 19,
    marginRight: 12,
  },
  detailValue: {
    color: Colors.neutral09,
    flex: 1.2,
    flexShrink: 1,
    lineHeight: 19,
    minWidth: 0,
    textAlign: 'right',
  },
  importantNotesList: {
    gap: 12,
    marginTop: 16,
  },
  importantNoteRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
  },
  importantNoteBullet: {
    backgroundColor: Colors.red10,
    borderRadius: 4,
    height: 8,
    marginRight: 11,
    marginTop: 6,
    width: 8,
  },
  importantNoteText: {
    color: Colors.neutral08,
    flex: 1,
    lineHeight: 20,
  },
  notesText: {
    color: Colors.neutral08,
    lineHeight: 20,
    marginTop: 10,
  },
  supportCard: {
    alignItems: 'flex-start',
    backgroundColor: Colors.red01,
    borderColor: Colors.red03,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    padding: 15,
  },
  supportIcon: {
    alignItems: 'center',
    backgroundColor: Colors.neutral01,
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    marginRight: 11,
    width: 36,
  },
  supportTextGroup: {
    flex: 1,
    minWidth: 0,
  },
  supportTitle: {
    color: Colors.neutral09,
    lineHeight: 21,
  },
  supportText: {
    color: Colors.neutral08,
    lineHeight: 19,
    marginTop: 2,
  },
  supportEmailLink: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 7,
    marginTop: 9,
    minHeight: 32,
    paddingHorizontal: 2,
  },
  supportEmailLinkPressed: {
    opacity: 0.65,
  },
  supportEmailText: {
    color: Colors.maroon10,
    lineHeight: 19,
    textDecorationLine: 'underline',
  },
  skeletonLayout: {
    gap: 12,
  },
  skeletonCard: {
    backgroundColor: Colors.neutral01,
    borderColor: Colors.neutral04,
    borderRadius: 16,
    borderWidth: 1,
    gap: 14,
    padding: 18,
  },
  skeletonSummary: {
    backgroundColor: Colors.maroon01,
  },
  skeletonHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  skeletonIdentity: {
    flex: 1,
    gap: 8,
  },
  skeletonMetrics: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  stateCard: {
    alignItems: 'center',
    backgroundColor: Colors.neutral01,
    borderColor: Colors.neutral04,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 24,
    paddingVertical: 30,
  },
  stateTitle: {
    color: Colors.neutral09,
    fontSize: FontSizes.medium,
    lineHeight: 23,
    marginTop: 12,
    textAlign: 'center',
  },
  stateDescription: {
    color: Colors.neutral07,
    lineHeight: 19,
    marginTop: 5,
    textAlign: 'center',
  },
  retryButton: {
    marginTop: 18,
    minWidth: 148,
  },
  emptyState: {
    marginTop: 12,
  },
});
