# Copy this file to config.toml and fill in local values.
# config.toml is gitignored and must not be committed.
# Settings related to how the application runs
[application]
  # Specifies how the application will run
  # Has a value of either 'development' or 'production'. Defaults to development
  environment = "development"

  # The name of the application
  # Has a string type. Defaults to 'wiremo-personal'
  name = "wiremo-personal"

  # Directory where log files will be placed
  # Has a path string type. Required
  log-directory = "./logs"

  # Address where the application's web component is located
  # Has an IP address string type or domain string type. Must include the protocol (http or https). Required
  domain = "http://localhost:3000"
  # domain = "http://192.168.5.244:3000"
  # domain = "http://192.168.50.139:3000"

  # Address where the application's API server is located
  # Has an IP address string type or domain string type. Must include the protocol (http or https). Required
  api-domain = "http://localhost:8800"
  # api-domain = "http://192.168.5.244:8040"
  # api-domain = "http://192.168.50.139:3000"

  # Determines whether the application forces logout on user idle time
  # Bool type. Set to true in production
  idle-time-enabled = false

  # Secret key used in [URLSafeTimedSerializer, ]
  secret_key = ""

  # Salt used in [URLSafeTimedSerializer, ]
  secret_salt = ""

  # Time in seconds for reset password token to expire. Default of 24 hours
  reset_password_expiration = 86400

  domain-port = "3000"

  # Settings related to how the application's JWT auth is configured
  [application.jwt]
    # Path to the ed25519 private key to be used for the application's JWT auth
    # Has a path string type. Required
    ed25519-pem = "./jwt.pem"

    # Path to the ed25519 public key to be used to verify whether a JWT's signature is valid
    # Has a path string type. Required
    ed25519-pub = "./jwt.pub"

    # Number of seconds before the token expires
    # Has an integer type. Defaults to 15000
    expiry = 15000

    # Number of seconds before a privilege-escalated token expires
    # Has an integer type. Defaults to 600
    escalated-token-expiry = 600

# Settings related to how the API server is served
[api-server]
  # Hostname for the API server
  # Has an IP address string type or domain string type. Required
  host = "0.0.0.0"

  # Indicates which port the API server is served
  # Has an integer type. Required only when the environment is in 'development' mode
  port = 8800

  # Indicates which port the API server's websocket endpoints are served
  # Has an integer type. Required only when the environment is in 'development' mode
  ws-port = 8810

  # Directory where images are uploaded
  # Has a path string type
  file-storage-path = "./files"

  # Secrets related to third-party services the API uses
  [api-server.secrets]
    # API token for https://ipinfo.io used for IP address identification
    # Has a string type. Required
    ip-info-token = ""

    # API token for https://sendgrid.com used to validate sign up email addresses
    # Has a string type. Required
    sendgrid-token = ""

# Third-party integration settings
[integrations]
  # Cloudflare Turnstile settings used as an invisible CAPTCHA-like way of identifying
  # whether a request made to the server is made by a robot or not
  [integrations.cloudflare-turnstile]
    # The server-side token used to validate the request made
    # Has a string type. Required
    # secret = ""
    secret = ""

    # The token used to identify a site
    # Has a string type. Required
    # sitekey = ""
    sitekey = ""

  # Settings related to Twilio
  [integrations.twilio]
    # Twilio account SID
    account-sid = ""

    # Twilio auth token
    auth-token = ""

    # ID for Verify service Wiremo account
    # for use in phone verification
    verify-sid-phone = ""

    # ID for Verify service Wiremo login
    # for use in login
    verify-sid-login = ""

    # ID for Verify service Wiremo
    # for use in other general purposes
    verify-sid-general = ""

    # Whether it calls the actual Verify API or just provide a mock response for sms channel
    # Toggle to false in production or if you want to test actual API during development
    sms-verify-mock-mode = true

  # Settings related to VGS
  [integrations.vgs]
    # CORS url for live use https for devlopment use http
    cors_url = "https://js.verygoodvault.com"

    # VGS implementation to check if the code is production or development
    live = "sandbox"

    # VGS vault ID
    # For identifying which vault to use for storing token information
    id = ""

    # VGS Inbound Route Proxy use for URL redirecting to the API server
    proxy = "/chard-wiremo"

  # Settings related to braintree
  [integrations.braintree]
    #
    version = "2020-09-14"

    #
    url = "https://payments.sandbox.braintree-api.com"

    #merchant id of the braintree settings
    merchant_id = ""

    #
    public_key = ""

    #
    private_key = ""

  # Settings related to enrollments
  [integrations.enrollments]
    url = ""

  # Settings related to helpscout beacon
  [integrations.beacon]
    #Beacon ID
    id = ""
    # id = ""

    #API Secret Key
    secret = ""
    # secret = ""

  # Settings related to refiner
  [integrations.refiner]
    #Project ID
    id = ""

    #Survey ID
    survey = ""

    #API Secret Key
    secret = ""

  [integrations.rollbar]
    # Indicates if the rollbar feature is enabled
    # Has a boolean type. Defaults to false
      enabled = false
    # The post_server_item key of a Rollbar project
    # Has a string type. Required
      access-token = ""

  # Settings related to Posthog
  [integrations.posthog_config]
    # Api key. Type string. Required
    # ""
    api_key = ""

    # Type boolean. Required. Whether service is enabled or not.
    # Default is true for production ONLY. Do not enable on dev mode unless testing.
    enabled = false

  # Settings related to google analytics
  [integrations.google_analytics]
    #Tracking ID. Type string. Required
    tracking_id = ""

    #Type boolean. Required. Prevent GA4 from being loaded or called
    test_mode = true

  # Settings related to meta
  [integrations.meta]
    pixel_id = ""

  [integrations.plaid]
  # client_id
    client_id = ""

  # secrey_key
    secret_key = ""

  # environment
    environment = "sandbox"

  # products of plaid that will be used
    products = "auth,identity"

  # countries that will be supported by plaid
    countries = "US,CA"

  # plaid redirect uri for redirection after OAuth institutions
    redirect_uri = ""

  # plaid webhook url
    webhook_url = ""

# Database connectivity settings
[database]
  # PostgreSQL-specific database connectivity settings
  [database.psql]
    # Connection string to the PostgreSQL database. Note that special characters
    #  such as '#', ':', and '@' in the password needs to be percent-encoded
    # Has a URI string type. Required
    connection-string = "postgres://aqwire:aqwire@localhost:5432/aqwire"

    # TLS Certificate for the PostgreSQL database. Uncomment the variable
    #  if the connection string requires a TLS certificate to connect to
    #  the PostgreSQL database instance.
    # Has a path string type. Optional
    #tls-cert = ""

    # PostgreSQL-specific database connectivity settings meant to be used for integration/unit testing.
    #  This object is optional, and the field conditions only apply if tests need to be run
    [database.psql.testing]
      # Connection string to the PostgreSQL database. Note that special characters
      #  such as '#', ':', and '@' in the password needs to be percent-encoded
      # Has a URI string type. Required
      connection-string = "postgres://aqwire:aqwire@localhost:5432/aqwire_test"

      # TLS Certificate for the PostgreSQL database. Uncomment the variable
      #  if the connection string requires a TLS certificate to connect to
      #  the PostgreSQL database instance.
      # Has a path string type. Optional
      # tls-cert = ""

    [test.data]
      # Test data for the integration tests that uses partner's API
      # customer-test-metadata = "{\"ckoCustomerId\": \"cus_5ia6ykgknoyunlrutrmjhisove\", \"mayaCustomerId\": \"e0c855e6-1b38-478e-9a5d-71c878bbd846\"}"
      # maya-card-test-metadata = "{\"bin\": \"54530100\", \"maya\": \"wNRdLNWQJk7Ly8obw8BWl2f5R4Gv4PSr5FLBlF13nGtqAj1lrr2v4I7SYi5PM7yb9ibxpHU7MtleQaRuFdDc72zrjBrJyzwByAYlGhmCEjJhRb0Vw8lfAWH1WXL5NLzduFRGHpjsw4BBo2lybhZeeCNttOq3sgRTzM\", \"mayaCustomerId\": \"e0c855e6-1b38-478e-9a5d-71c878bbd846\", \"tokenized_security_code\": \"tok_sandbox_iD3VuZnPVohDPiiDvqF26a\"}"
      customer-test-metadata = "{}"
      maya-card-test-metadata = "{}"

  # Redis-specific database connectivity settings
  [database.redis]
    # Hostname of the Redis database
    # Has a string type. Required
    host = "localhost"

    # Port number of the Redis database
    # Has an integer type. Defaults to 6379
    port = 6379

    # Password for the Redis database connection
    # Has a string type. Defaults to ''
    password = ""

    # The Redis DB index the application will utilize
    # Has an integer type. Defaults to 0
    db-index = 0

    # Redis-specific database connectivity settings meant to be used for integration/unit testing
    #  This object is optional, and the field conditions only apply if tests need to be run
    [database.redis.testing]
      # Hostname of the Redis database
      # Has a string type. Required
      host = "localhost"

      # Port number of the Redis database
      # Has an integer type. Defaults to 6379
      port = 6379

      # Password for the Redis database connection
      # Has a string type. Defaults to ''
      password = ""

      # The Redis DB index the application will utilize
      # Has an integer type. Defaults to 10
      #################################################
      ################     WARNING     ################
      ###  DO NOT ATTEMPT TO MAKE THE DB INDEX THE  ###
      ###  SAME AS THE ONE USED IN YOUR ACTUAL APP  ###
      ###  INSTANCE! THE TEST RUNNER WILL CLEAR ALL ###
      ###    THE KEYS IN REDIS, BREAKING YOUR DB!   ###
      #################################################
      db-index = 9

  # Mongo-specific database connectivity settings
  [database.mongo]
    # Connection string to the Mongo database. Note that special characters
    #  such as '#', ':', and '@' in the password needs to be percent-encoded
    # Has a URI string type. Required
    connection-string = "mongodb://localhost:27017"

    # TLS Certificate for the Mongo database. Uncomment the variable
    #  if the connection string requires a TLS certificate to connect to
    #  the Mongo database instance.
    # Has a path string type. Optional
    tls-cert = ""