export const API_PATHS = {
  auth: {
    login: 'auth/',
    resetPassword: 'auth/reset-password',
    resetPasswordConfirm: 'auth/reset-password-confirm',
    signup: '/person/',
    verifyEmail: '/person/verify/email-verification',
    resendOtp: '/person/resend-code/email-verification'
  },
  dashboard: {
    biller: 'biller/',
    getBillerConfig: (id: number, key: string) => `biller/${id}/config/${encodeURIComponent(key)}`,
    getBillerProjects: (id: number) => `biller/${id}/project`,
    getBillerPaymentTypes: (id: number) => `biller/${id}/config/paymentTypes`,
    getBillerPropertyTypes: (id: number) => `biller/${id}/config/propertyTypes`,
    getBillerSalesChannel: (id: number) => `biller/${id}/config/salesChannels`,
    getBillerPaymentModes: (id: number) => `biller/${id}/config/paymentModes`,
    getBillerPaymentOptions: (id: number) => `biller/${id}/config/paymentOptions`,
    getBillerMonths: (id: number) => `biller/${id}/config/months`,
    getBillerPaymentYears: (id: number) => `biller/${id}/config/paymentYears`,
    getBillerChargeTypes: (id: number) => `biller/${id}/config/chargeTypes`,
  },
  settings: {
    individual: 'customer/individual',
    updateEmail: 'person/email',
    updateEmailConfirm: 'person/change-email',
    updateProfile: 'person/profile', 
    updateAddress: 'customer/add-address/individual',
    updatePassword: 'auth/',
  },
  bills: {
    base: 'bills/',
    getDetail: (id: string) => `bills/${id}`,
    getBiller: (id: number) => `biller/${id}`,
  },
  paymentMethods: {
    get: '/payment-methods/get-payment-methods',
    add: '/payment-methods/add-card-payment',
    update: (id: string) => `payment-methods/${id}`,
    delete: (id: string) => `payment-methods/${id}`,
    directDebitLink: (channelCode: string) => `/payment-methods/direct-debit/link/${channelCode}`,
    directDebitCharge: '/payment-methods/direct-debit/charge',
    directDebitValidateOtp: '/payment-methods/direct-debit/validate-otp',
    directDebitResendOtp: '/payment-methods/direct-debit/resend-otp',
  },
  transactions: {
    base: 'transactions/',
    detail: (id: string) => `transactions/${id}`,
    last: (id: string) =>  `transactions/last/${id}`,
    pay: (transactionId: string) => `/transactions/${transactionId}/pay`,
    payWithCard: '/transactions/pay-with-card',
    payWithQrph: '/transactions/pay-with-qrph',
    verifyQrph: (transactionId: string) => `/transactions/${transactionId}/qrph/verify`,
    cancelQrph: (transactionId: string) => `/transactions/${transactionId}/qrph/cancel`,
    payWithPayPal: '/transactions/pay-with-paypal',
    capturePayPal: (transactionId: string) => `/transactions/${transactionId}/paypal/capture`,
    cancelPayPal: (transactionId: string) => `/transactions/${transactionId}/paypal/cancel`,
  },
  enrollments: {
    base: 'enrollments',
    transactions: 'enrollments/transactions',
  },
  merchant: {
    get: '/merchants?supports=enrollment&affiliation=non-ayala',
    getPayment: (id: string) => `/merchants/${id}/payment`,
    getLandingConfig: (id: string) => `/merchants/${id}/config/landing`,
    getPaymentTypes: (id: string) => `/merchants/${id}/payment-types`,
    getMerchantById: (id: string) => `/merchants/${id}`,
    getPaymentFormConfig: (id: string) => `/merchants/${id}/config/forms/payment`,
    getEnrollmentFormConfig: (id: string) => `/merchants/${id}/config/forms/enrollment`,
    getProjects: (id: string) => `/merchants/${id}/projects`,
    postTransaction: (id: string) => `/merchants/${id}/transactions`,
    postEnrollment: (id: string) => `/merchants/${id}/enrollments`,
    getTransaction: (id: string, transactionId: string) => `/merchants/${id}/transactions/${transactionId}`,
    getEnrollment: (id: string, enrollmentId: string) => `/merchants/${id}/enrollments/${enrollmentId}`,
    getTransactionPaymentBin: (id: string, transactionId: string, binNumber: string) => `/merchants/${id}/transactions/${transactionId}/payment/bin/${binNumber}`,
    getEnrollmentPaymentBin: (id: string, transactionId: string, binNumber: string) => `/merchants/${id}/enrollments/${transactionId}/payment/bin/${binNumber}`,
    getReceipt: (id: string, referenceId: string) => `/merchants/${id}/receipts/${referenceId}`,
    getEnrollmentReceipt: (id: string, referenceId: string) => `/merchants/${id}/enrollments/receipts/${referenceId}`,
    getReceiptKeys: (id: string, transactionId: string) => `/merchants/${id}/receipts/${transactionId}/keys`,
    postTransactionPaymentCko: (id: string, transactionId: string) => `/merchants/${id}/transactions/${transactionId}/payment/cko`,
    postTransactionPaymentVault: (id: string, transactionId: string) => `/merchants/${id}/transactions/${transactionId}/payment/vault`,
    postEnrollmentPaymentVault: (id: string, enrollmentId: string) => `/merchants/${id}/enrollments/${enrollmentId}/payment/vault`,
    postEnrollmentEnroll: (id: string, enrollmentId: string) => `/merchants/${id}/enrollments/${enrollmentId}/enroll`,
  },
}
